///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest12
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest12Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f002c058-c881-4aa2-bdae-f521cef0c60c")]
    public partial class MyTest12Repository : RepoGenBaseFolder
    {
        static MyTest12Repository instance = new MyTest12Repository();
        MyTest12RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest12Repository element repository.
        /// </summary>
        [RepositoryFolder("f002c058-c881-4aa2-bdae-f521cef0c60c")]
        public static MyTest12Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest12Repository() 
            : base("MyTest12Repository", "/", null, 0, false, "f002c058-c881-4aa2-bdae-f521cef0c60c", ".\\RepositoryImages\\MyTest12Repositoryf002c058.rximgres")
        {
            _applicationundertest = new MyTest12RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f002c058-c881-4aa2-bdae-f521cef0c60c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("0f65e22a-83bb-4de7-a6e0-a05c4228b6de")]
        public virtual MyTest12RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest12RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("0f65e22a-83bb-4de7-a6e0-a05c4228b6de")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputtagsInfo;
            RepoItemInfo _trystudioInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "0f65e22a-83bb-4de7-a6e0-a05c4228b6de", "")
            {
                _inputtagsInfo = new RepoItemInfo(this, "InputTagS", ".//div[#'page-container']/div[@id='et-boc']/header/div/div[1]//form[@action='https://www.ranorex.com/']/?/?/input[@name='s']", ".//div[#'et-boc']//input[@name='s']", 30000, null, "3bc246a0-32e0-4714-9421-816b55203662");
                _trystudioInfo = new RepoItemInfo(this, "TryStudio", ".//div[#'page-container']/div[@id='et-boc']/header/div/div[2]/div/div[2]/div[3]/a[@innertext='Try Studio']", ".//div[#'et-boc']//a[@innertext='Try Studio']", 30000, null, "f6aabe0f-8bab-4051-998a-fcb946d3c96c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0f65e22a-83bb-4de7-a6e0-a05c4228b6de")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0f65e22a-83bb-4de7-a6e0-a05c4228b6de")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputTagS item.
            /// </summary>
            [RepositoryItem("3bc246a0-32e0-4714-9421-816b55203662")]
            public virtual Ranorex.InputTag InputTagS
            {
                get
                {
                    return _inputtagsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagS item info.
            /// </summary>
            [RepositoryItemInfo("3bc246a0-32e0-4714-9421-816b55203662")]
            public virtual RepoItemInfo InputTagSInfo
            {
                get
                {
                    return _inputtagsInfo;
                }
            }

            /// <summary>
            /// The TryStudio item.
            /// </summary>
            [RepositoryItem("f6aabe0f-8bab-4051-998a-fcb946d3c96c")]
            public virtual Ranorex.ATag TryStudio
            {
                get
                {
                    return _trystudioInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TryStudio item info.
            /// </summary>
            [RepositoryItemInfo("f6aabe0f-8bab-4051-998a-fcb946d3c96c")]
            public virtual RepoItemInfo TryStudioInfo
            {
                get
                {
                    return _trystudioInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
