name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build_and_test:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'MyTest12.sln'

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        # Semantic version range syntax or exact version of a dotnet version
        dotnet-version: '6.x'


    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build app for release
      run: msbuild MyTest12.csproj
      
    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx"
      
    - name: Dotnet Test Reporter
      uses: bibipkins/dotnet-test-reporter@v1.4.1
            
     
 

   
          
