name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'MyTest12.sln'

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0

    - name: Restore dependencies
      run: dotnet restore MyTest12.sln

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
       msbuild-architecture: x64
       vswhere-path: 'C:/Program Files (x86)/Microsoft Visual Studio/Installer'

    - name: Run Ranorex Tests
      run: msbuild MyTest12.sln

   # - name: Run Unit Tests
    #  run: dotnet test MyTest12.sln --configuration ${{env.BUILD_CONFIG}} --logger:trx --results-directory:./TestResults/*.trx

    - name: Test
      run: dotnet test MyTest12.sln --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx"
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

   # - name: Dotnet Test Reporter
 
   #   uses: bibipkins/dotnet-test-reporter@v1.4.1
   #   with:
    #    github-token:
      #   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
      #  results-path: 
       #  ./Reports
      


          
