# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
           dotnet-version: | 
             3.1.x
             5.0.x 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
       vswhere-path: 'C:/Program Files (x86)/Microsoft Visual Studio/Installer'
    - name: Run Ranorex Tests
      run: msbuild 'C:\Users\festi\Documents\Ranorex\RanorexStudio Projects\MyTest12\MyTest12'
