
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted


    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
       msbuild-architecture: x64
       vswhere-path: 'C:/Program Files (x86)/Microsoft Visual Studio/Installer'
    - name: Run Ranorex Tests
      run: msbuild MyTest12.sln

          
