on:  
  push:  
    branches: [ "main" ]  
  pull_request:  
    branches: [ "main" ]  
   
jobs:  
  build:  
   
    runs-on:  self-hosted
   
    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  
      - name: Install dependencies  
        run: dotnet restore  
      - name: Setup .NET  
        uses: actions/setup-dotnet@v4  
      - name: setup-msbuild  
        uses: microsoft/setup-msbuild@v2  
      - name: Install dependencies  
        run: dotnet restore MyTest12.sln  
      - name: Build  
        run: dotnet msbuild MyTest12.sln  
      - name: Test with the dotnet CLI  
        run: dotnet test MyTest12.sln
   
          
