name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'MyTest12.sln'

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0

 #   - name: Restore dependencies
 #     run: dotnet restore MyTest12.sln

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
       msbuild-architecture: x64
       vswhere-path: 'C:/Program Files (x86)/Microsoft Visual Studio/Installer'

    - name: Run Ranorex Tests
      run: msbuild MyTest12.sln

    - name: Run the solution
      run: MyTest12/bin/Debug/MyTest12.exe

 #   - name: Run Unit Tests
  #    run: dotnet test MyTest12.sln --configuration ${{env.BUILD_CONFIG}} --logger:trx --results-directory:./TestResults
      
