# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: label-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: dotnet restore
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
       
      - name: Install dependencies
        run: dotnet restore MyTest12.sln
      - name: Build
        run: msbuild MyTest12.sln
      - name: Test with the dotnet CLI
        run: dotnet test MyTest12.sln
    
    
     
 

   
          
