name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'MyTest12.sln'

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0

    - name: Restore dependencies
      run: dotnet restore MyTest12.sln

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
       msbuild-architecture: x64
       vswhere-path: 'C:/Program Files (x86)/Microsoft Visual Studio/Installer'

    - name: Run Ranorex Tests
      run: msbuild MyTest12.sln

    - name: Test
      run: dotnet test MyTest12.sln --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx"
      
    - name: Dotnet Test Reporter
      uses: bibipkins/dotnet-test-reporter@v1.4.1

          
