name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build_and_test:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'MyTest12.sln'

    runs-on: label-10

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2


    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION
      
    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true
      
    - name: Dotnet Test Reporter
      uses: bibipkins/dotnet-test-reporter@v1.4.1
            
     
 

   
          
